export * from './usePatient'
export * from './usePatients'
export * from './useDisease'
export * from './useTreatment'
export * from './useConsultation'
export * from './useQuotation'
export * from './useBackground'
export * from './useOdontogram'
