import { Card, Grid, Typography } from '@mui/material'
import { Inter } from 'next/font/google'
import Head from 'next/head'

import { Layout } from '@/layout'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Saludentis App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <Card>
          <Grid container spacing={2} >
            <Grid item xs={6} display={'flex'} justifyContent={'center'}>
              <Typography variant='h2'>Paciente Nuevo</Typography>
            </Grid>
            <Grid item xs={6} display={'flex'} justifyContent={'center'}>
              <Typography variant='h2'>Paciente</Typography>
            </Grid>
          </Grid>
        </Card>
      </Layout>
    </>
  )
}
