import { ArrowCircleRightOutlined } from '@mui/icons-material'
import { Box, Button, Card, CardActionArea, CardContent, FormControl, FormHelperText, Grid, InputLabel, Link, MenuItem, NativeSelect, Select, SelectChangeEvent, Typography } from '@mui/material'
import Head from 'next/head'
import NextLink from 'next/link'
import { useState } from 'react'

import { Layout } from '@/layout'

const patients = [
  {
    id: 1,
    name: 'Juan Perez',
  },
  {
    id: 2,
    name: 'Maria Lopez',
  },
  {
    id: 3,
    name: 'Carlos Rodriguez',
  },
]

export default function Home() {
  const [age, setAge] = useState('')

  const handleChange = (event: SelectChangeEvent) => {
    setAge(event.target.value)
  }
  return (
    <>
      <Head>
        <title>Saludentis App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Layout>
        <Card sx={{
          padding: 5,
          width: {
            xs: '100%',
            sm: '80%',
          }
        }}>
          <Grid container flexDirection={'row'} display={'flex'}>
            <Grid item xs={12} sm={6} display={'flex'} justifyContent={'center'} alignItems={'center'} flexDirection={'column'}>
              <Card sx={{
                boxShadow: 'none'
              }}>
                <CardContent>
                  <Typography variant="h5" component="div" textAlign={'center'}>
                    Paciente Nuevo
                  </Typography>
                  <Grid item display={'flex'} justifyContent={'space-evenly'} alignItems={'center'} mt={5} flexDirection={'row'}>
                    <Grid mr={4}>
                      <Button variant='contained' sx={{
                        padding: '1rem'
                      }}>
                        <NextLink href={'/'} passHref legacyBehavior>
                          <Link display={'flex'} alignItems={'center'}>
                            <Typography variant='h6' color={'white'}>Niño</Typography>
                          </Link>
                        </NextLink>
                      </Button>
                    </Grid>
                    <Box ml={4}>
                      <Button variant='contained' sx={{
                        padding: '1rem'
                      }}>
                        <NextLink href={'/asd'} passHref legacyBehavior>
                          <Link display={'flex'} alignItems={'center'}>
                            <Typography variant='h6' color={'white'}>Adulto</Typography>
                          </Link>
                        </NextLink>
                      </Button>
                    </Box>
                  </Grid>
                </CardContent>
              </Card>
            </Grid>
            <Grid item xs={12} sm={6} display={'flex'} flexDirection={'column'} justifyContent={'center'} padding={0}>
              <Card sx={{
                boxShadow: 'none'
              }}>
                <CardContent>
                  <Typography variant="h5" component="div" textAlign={'center'} mb={5}>
                    Paciente
                  </Typography>
                  <FormControl sx={{ width: '100%' }}>
                    <InputLabel id="select-label">Nombre</InputLabel>
                    <Select
                      labelId="select-label"
                      id="select"
                      fullWidth
                      label="Nombre"
                      onChange={handleChange}
                    >
                      {patients.map((patient) => (
                        <MenuItem key={patient.id} value={patient.id}>
                          {patient.name}
                        </MenuItem>
                      ))}
                    </Select>
                  </FormControl>
                  <Box display={'flex'} flexDirection={'column'} alignItems={'center'}>
                    <Box my={4}>
                      <Button
                        variant='contained'
                        color='primary'
                        endIcon={<ArrowCircleRightOutlined />}
                        sx={{
                          padding: '1rem'
                        }}
                      >
                        <Typography variant='h6' color={'white'}>Ingresar</Typography>
                      </Button>
                    </Box>
                    <NextLink href={'https://calendar.google.com/calendar'} passHref legacyBehavior>
                      <Link display={'flex'} alignItems={'center'}>
                        <Typography variant='h6'>Calendario</Typography>
                      </Link>
                    </NextLink>
                  </Box>
                </CardContent>
              </Card>
            </Grid>
          </Grid>
        </Card>
      </Layout >
    </>
  )
}
