export const seedTreatments = [
    { id: 1, description: 'Resina compuesta Una superficie', price: 200.00 },
    { id: 2, description: 'Resina compuesta Dos o más superficies', price: 250.00 },
    { id: 3, description: 'Sellante fosas y fisuras', price: 75.00 },
    { id: 4, description: 'Incrustación', price: 600.00 },
    { id: 5, description: 'Prótesis fija metal porcelana', price: 1000.00 },
    { id: 6, description: 'Prótesis removible acrílico', price: 600.00 },
    { id: 7, description: 'Prótesis removible Valplast', price: 2000.00 },
    { id: 8, description: 'Prótesis removible cromo-cobalto', price: 2000.00 },
    { id: 9, description: 'Prótesis removible híbrida', price: 2700.00 },
    { id: 10, description: 'Prótesis fija E-Max', price: 2000.00 },
    { id: 11, description: 'Prótesis fija Zirconio', price: 2500.00 },
    { id: 12, description: 'Limpieza dental adulto', price: 300.00 },
    { id: 13, description: 'Limpieza dental niño', price: 200.00 },
    { id: 14, description: 'Resina compuesta niño', price: 175.00 },
    { id: 15, description: 'Mantenedor de espacio', price: 500.00 },
    { id: 16, description: 'Pulpotonía', price: 150.00 },
    { id: 17, description: 'Corona de acero', price: 250.00 },
    { id: 18, description: 'Exodoncia', price: 150.00 },
    { id: 19, description: 'Cirugía cordales', price: 850.00 },
    { id: 20, description: 'Tratamiento de coductos uniradicular', price: 800.00 },
    { id: 21, description: 'Tratamiento de coductos multiradicular', price: 1200.00 },
    { id: 22, description: 'Nebulización', price: 150.00 },
    { id: 23, description: 'Terapia Neural', price: 150.00 },
    { id: 24, description: 'Consulta', price: 150.00 },
    { id: 25, description: 'Guarda Oclusal', price: 300.00 },
    { id: 26, description: 'Exodoncia Cordal', price: 200.00 },
    { id: 27, description: 'Cementación Brackets Superior', price: 900.00 },
    { id: 28, description: 'Cementación Brackets Inferior', price: 900.00 },
    { id: 29, description: 'Cita control ortodoncia', price: 250.00 },
]

export const seedDisieases = [
    { id: 1, detail: 'Caries Dental Superficial' },
    { id: 2, detail: 'Caries Dental Profunda' },
    { id: 3, detail: 'Resina Compuesta' },
    { id: 4, detail: 'Filtración Resina Compuesta' },
    { id: 5, detail: 'Amalgama Dental' },
    { id: 6, detail: 'Filtración Amalgama Dental' },
    { id: 7, detail: 'Abración Dental' },
    { id: 8, detail: 'Abfracción Dental' },
    { id: 9, detail: 'Pieza Ausente' },
    { id: 10, detail: 'Mal Pisición Dental' },
    { id: 11, detail: 'Absceso Dental' },
    { id: 12, detail: 'Prótesis Fija' },
    { id: 13, detail: 'Extruido' },
    { id: 14, detail: 'Endodoncia en Buen Estado' },
    { id: 15, detail: 'Endodoncia en Mal Estado' },
    { id: 16, detail: '3ra Molar Retenida' },
    { id: 17, detail: '3ra Molar Inclinada' },
    { id: 18, detail: 'Chasquido' },
    { id: 19, detail: 'Desviación Izquierda' },
    { id: 20, detail: 'Desviación Derecha' },
    { id: 21, detail: 'Dolor Derecha' },
    { id: 22, detail: 'Dolor Izquierda' },
    { id: 23, detail: 'Gingivitis Leve' },
    { id: 24, detail: 'Gingivitis Moderada' },
    { id: 25, detail: 'Gingivitis Severa' },
    { id: 26, detail: 'Periodontitis' },
    { id: 27, detail: 'Diente Sano' },
    { id: 28, detail: 'Detox' },
    { id: 29, detail: 'Consulta' },
    { id: 30, detail: 'Trastorno Neuromuscular' }
]